version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile  # Dockerfile do seu app Node
    image: m2_nodejs
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_NAME: plataforma_consultas
      HOST: 0.0.0.0
    ports:
      - "3000:3000"

  mysql:
    build:
      context: .
      dockerfile: dockerfile.mysql  # Dockerfile do MySQL
    environment:
      MYSQL_DATABASE: plataforma_consultas
      MYSQL_ROOT_PASSWORD: secret
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    image: m2_mysql
    volumes:
      - mysql-data-PMC:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  nginx:
    build:
      context: ../frontend 
      dockerfile: dockerfile # Dockerfile do Nginx, com a configuração para SPA
    image: m2_nginx
    depends_on:
      - app
    ports:
      - "3001:80"

volumes:
  mysql-data-PMC:
