services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    image: nodejs_teste
    depends_on:
      mysql: # Garante que o MySQL esteja pronto antes do Node.js
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_NAME: plataforma_consultas
      HOST: 0.0.0.0
    ports:
      - "3000:3000"

  mysql:
    build:
      context: .
      dockerfile: dockerfile.mysql
    environment:
      MYSQL_DATABASE: plataforma_consultas         # Nome do banco de dados a ser criad0
      MYSQL_ROOT_PASSWORD: secret
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    image: mysql_teste
    volumes:
      - mysql-data-PMC:/var/lib/mysql # Volume persistente para dados do banco
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql-data-PMC:
